"""Regenerate the frozen ``DEFAULT_STATE_MULTIPLIERS`` table for the role-shock
scenario-mixture simulator, from committed code instead of an ephemeral
``/tmp`` script.

Previously the frozen table in ``nflvalue/fantasy/role_state.py`` could only be
regenerated by ``/tmp/exp_roleshock/make_multipliers.py`` +
``make_within_var.py``, which do not live in the repository -- a reproducibility
hole flagged in ``reports/role_shock_engine.md``.  This module reconstructs the
exact recipe documented above the constant:

    relative_state_multipliers(estimate_state_multipliers(frame, max_season))
    + opportunity_var = robust ((q3 - q1) / 1.349) ** 2 of the stable-normalized
      realized opportunity ratio within each position x state (train rows;
      sparse cells (n < 25) inherit the cross-position median of that state).

Both building blocks (``estimate_state_multipliers`` and
``relative_state_multipliers``) are already committed in ``role_state.py``; only
the variance channel and the assembly lived off-repo.  The numbers are frozen on
train seasons only (default 2019-2022), so the simulator keeps no runtime data
dependency and no test-season leakage.

Usage::

    python -m scripts.build_role_multipliers \
        --frame reports/fantasy_feature_frame_v2.parquet \
        --max-season 2022 --json data/role_state_multipliers.json

With ``--print`` it emits a Python literal ready to paste over the frozen
constant.  This script requires the historical feature frame v2; it is not part
of the data-independent CI list, but its pure helpers are unit-tested in
``tests/test_role_multipliers.py``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Mapping

import numpy as np
import pandas as pd

from nflvalue.fantasy.role_state import (
    ACTIVE_STATES,
    POSITIONS,
    _numeric,
    estimate_state_multipliers,
    relative_state_multipliers,
)

ROBUST_IQR_TO_SIGMA = 1.349


def stable_normalized_opportunity_ratio(frame: pd.DataFrame) -> pd.Series:
    """Realized opportunity ratio divided by the position's ``stable`` median.

    Mirrors ``estimate_state_multipliers``: ratio = opportunities /
    max(pre_opportunities_ewm4, 1).  Normalizing by the same position's stable
    median cancels the denominator clip, matching the ``opportunity`` channel of
    ``relative_state_multipliers``.
    """

    labels = frame["role_state_label"].astype(str)
    ratio = _numeric(frame["opportunities"]) / _numeric(
        frame["pre_opportunities_ewm4"]
    ).clip(lower=1.0)
    normalized = pd.Series(np.nan, index=frame.index, dtype=float)
    for position in POSITIONS:
        pos_rows = frame["position"].eq(position)
        stable_rows = pos_rows & labels.eq("stable")
        stable_median = float(ratio[stable_rows].median()) if stable_rows.any() else 1.0
        stable_median = stable_median if stable_median > 1e-6 else 1.0
        normalized[pos_rows] = ratio[pos_rows] / stable_median
    return normalized


def _robust_var(values: pd.Series) -> float:
    clean = values.dropna()
    if len(clean) < 2:
        return 0.0
    q1, q3 = np.quantile(clean, [0.25, 0.75])
    return float(((q3 - q1) / ROBUST_IQR_TO_SIGMA) ** 2)


def opportunity_variance_table(
    frame: pd.DataFrame, max_season: int, *, min_cell: int = 25
) -> dict[str, float]:
    """Per position x state robust variance of the stable-normalized ratio.

    Sparse cells (< ``min_cell`` train rows) inherit the cross-position median
    variance of the same state, exactly as the frozen constant documents.
    """

    train = frame[
        frame["season"].astype(int).le(max_season)
        & frame["model_eligible"].fillna(False)
        & frame["played"].astype(bool)
    ].copy()
    labels = train["role_state_label"].astype(str)
    normalized = stable_normalized_opportunity_ratio(train)
    cells: dict[str, float] = {}
    counts: dict[str, int] = {}
    for position in POSITIONS:
        for state in ACTIVE_STATES:
            mask = train["position"].eq(position) & labels.eq(state)
            counts[f"{position}:{state}"] = int(mask.sum())
            cells[f"{position}:{state}"] = _robust_var(normalized[mask])
    # cross-position median per state for sparse-cell fallback
    state_median = {
        state: float(np.median([
            cells[f"{position}:{state}"] for position in POSITIONS
            if counts[f"{position}:{state}"] >= min_cell
        ] or [0.0]))
        for state in ACTIVE_STATES
    }
    for position in POSITIONS:
        for state in ACTIVE_STATES:
            key = f"{position}:{state}"
            if counts[key] < min_cell:
                cells[key] = state_median[state]
    return cells


def build_state_multiplier_table(
    frame: pd.DataFrame, max_season: int = 2022
) -> dict[str, dict[str, float]]:
    """Full ``DEFAULT_STATE_MULTIPLIERS``-shaped table incl. ``opportunity_var``."""

    raw = estimate_state_multipliers(frame, max_season=max_season)
    relative = relative_state_multipliers(raw)
    variance = opportunity_variance_table(frame, max_season=max_season)
    table: dict[str, dict[str, float]] = {}
    for position in POSITIONS:
        for state in ACTIVE_STATES:
            key = f"{position}:{state}"
            cell = dict(relative[key])
            cell["opportunity_var"] = round(variance[key], 3)
            for channel in ("opportunity", "target", "carry"):
                if channel in cell:
                    cell[channel] = round(float(cell[channel]), 3)
            table[key] = cell
    return table


def _as_python_literal(table: Mapping[str, Mapping[str, float]]) -> str:
    lines = ["DEFAULT_STATE_MULTIPLIERS = {"]
    for key, cell in table.items():
        body = ", ".join(f'"{k}": {v}' for k, v in cell.items())
        lines.append(f'    "{key}": {{{body}}},')
    lines.append("}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--frame", default="reports/fantasy_feature_frame_v2.parquet")
    parser.add_argument("--max-season", type=int, default=2022)
    parser.add_argument("--json", default="data/role_state_multipliers.json")
    parser.add_argument("--print", action="store_true", help="emit a Python literal")
    args = parser.parse_args(argv)

    frame = pd.read_parquet(args.frame)
    table = build_state_multiplier_table(frame, max_season=args.max_season)
    out = Path(args.json)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(table, indent=2, sort_keys=True) + "\n")
    if args.print:
        print(_as_python_literal(table))
    else:
        print(f"wrote {out} ({len(table)} cells, max_season={args.max_season})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
